### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by jpsingleton** [ChrisMissal/Formo#41]
Does Formo support or plan to support .NET Core?

The configuration system has [changed a lot](https://docs.asp.net/en/latest/fundamentals/configuration.html) but I really like how I can bind to a statically compiled object with Formo. Is Formo completely replaced by [options objects](https://docs.asp.net/en/latest/fundamentals/configuration.html#options-config-objects) or is there room for some advanced stuff? For example, connection strings.

**Comment by ChrisMissal** [comment]
I really like what they've done with the new Configuration system. It contains a lot of what I planned for Formo. That said, I don't have plans to add support for .NET Core, but I'm also not opposed to it if enough people are interested. I feel like the Options objects are a fine replacement for Formo to be quite honest.

**Comment by jpsingleton** [comment]
OK, cool. I'll close this then.
